version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "weekly"
    groups:
      site-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "nuget"
    directory: "/tests"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
