//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextAdventures.Utility.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextAdventures.Utility.Language.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Else.
        /// </summary>
        internal static string EditorAddElse {
            get {
                return ResourceManager.GetString("EditorAddElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Else If.
        /// </summary>
        internal static string EditorAddElseIf {
            get {
                return ResourceManager.GetString("EditorAddElseIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add link to.
        /// </summary>
        internal static string EditorAddLinkTo {
            get {
                return ResourceManager.GetString("EditorAddLinkTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string EditorBrowseButton {
            get {
                return ResourceManager.GetString("EditorBrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Games (*.aslx)|*.aslx|All files|*.*.
        /// </summary>
        internal static string EditorBrowseEditFilter {
            get {
                return ResourceManager.GetString("EditorBrowseEditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Games|*.quest;*.quest-save;*.aslx;*.asl;*.cas;*.qsg|All files|*.*.
        /// </summary>
        internal static string EditorBrowseFilter {
            get {
                return ResourceManager.GetString("EditorBrowseFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string EditorCancelButton {
            get {
                return ResourceManager.GetString("EditorCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot mix element types in the clipboard.
        /// </summary>
        internal static string EditorCannotMixElementTypesInClipboard {
            get {
                return ResourceManager.GetString("EditorCannotMixElementTypesInClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t play sound that is both synchronous and looped.
        /// </summary>
        internal static string EditorCantPlaySound {
            get {
                return ResourceManager.GetString("EditorCantPlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the language, Quest must be restarted. Would you like to continue?.
        /// </summary>
        internal static string EditorChangeLangRestartContinue {
            get {
                return ResourceManager.GetString("EditorChangeLangRestartContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also create exit in the other direction.
        /// </summary>
        internal static string EditorChkCorresponding {
            get {
                return ResourceManager.GetString("EditorChkCorresponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a walkthrough to run:.
        /// </summary>
        internal static string EditorChooseAWalktroughToRun {
            get {
                return ResourceManager.GetString("EditorChooseAWalktroughToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a type to add.
        /// </summary>
        internal static string EditorChooseTypeToAdd {
            get {
                return ResourceManager.GetString("EditorChooseTypeToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a walkthrough to run:.
        /// </summary>
        internal static string EditorChooseWalkthrough {
            get {
                return ResourceManager.GetString("EditorChooseWalkthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all items.
        /// </summary>
        internal static string EditorClearAllItems {
            get {
                return ResourceManager.GetString("EditorClearAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string EditorCmdDelete {
            get {
                return ResourceManager.GetString("EditorCmdDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit in the other direction already exists.
        /// </summary>
        internal static string EditorCorresponding {
            get {
                return ResourceManager.GetString("EditorCorresponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create exit.
        /// </summary>
        internal static string EditorCreate {
            get {
                return ResourceManager.GetString("EditorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create exit in the other direction.
        /// </summary>
        internal static string EditorCreateCorresponding {
            get {
                return ResourceManager.GetString("EditorCreateCorresponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an exit:.
        /// </summary>
        internal static string EditorCreateExitTitle {
            get {
                return ResourceManager.GetString("EditorCreateExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create local copy of &apos;{0}&apos;.
        /// </summary>
        internal static string EditorCreateLocalCopy {
            get {
                return ResourceManager.GetString("EditorCreateLocalCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create &quot;look&quot; direction.
        /// </summary>
        internal static string EditorCreateLookOnly {
            get {
                return ResourceManager.GetString("EditorCreateLookOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows players to look in this direction, but not move this way..
        /// </summary>
        internal static string EditorCreateLookOnlyDesc {
            get {
                return ResourceManager.GetString("EditorCreateLookOnlyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or create a &quot;look&quot; direction:.
        /// </summary>
        internal static string EditorCreateLookOnlyTitle {
            get {
                return ResourceManager.GetString("EditorCreateLookOnlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete downloaded file.
        /// </summary>
        internal static string EditorDeleteDownloadedFile {
            get {
                return ResourceManager.GetString("EditorDeleteDownloadedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A different file called {0} already exists in the game folder.\n\nWould you like to overwrite it?.
        /// </summary>
        internal static string EditorDifferentFileOverrideIt {
            get {
                return ResourceManager.GetString("EditorDifferentFileOverrideIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exit selected.
        /// </summary>
        internal static string EditorDirectionNoSelect {
            get {
                return ResourceManager.GetString("EditorDirectionNoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected exit is not a compass direction.
        /// </summary>
        internal static string EditorDirectionSelect {
            get {
                return ResourceManager.GetString("EditorDirectionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditorEdit {
            get {
                return ResourceManager.GetString("EditorEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element is not defined in a library.
        /// </summary>
        internal static string EditorElementIsNotDefinedInLibrary {
            get {
                return ResourceManager.GetString("EditorElementIsNotDefinedInLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Else.
        /// </summary>
        internal static string EditorElse {
            get {
                return ResourceManager.GetString("EditorElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Else If.
        /// </summary>
        internal static string EditorElseIf {
            get {
                return ResourceManager.GetString("EditorElseIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the new attribute.
        /// </summary>
        internal static string EditorEnterNameAttribute {
            get {
                return ResourceManager.GetString("EditorEnterNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the new verb.
        /// </summary>
        internal static string EditorEnterNameForNewVerb {
            get {
                return ResourceManager.GetString("EditorEnterNameForNewVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error running command.
        /// </summary>
        internal static string EditorErrorRunningCommand {
            get {
                return ResourceManager.GetString("EditorErrorRunningCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - walkthrough halted:.
        /// </summary>
        internal static string EditorErrorWalkthroughHalted {
            get {
                return ResourceManager.GetString("EditorErrorWalkthroughHalted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create folder: .
        /// </summary>
        internal static string EditorFailedCreateFolder {
            get {
                return ResourceManager.GetString("EditorFailedCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load game due to the following errors:.
        /// </summary>
        internal static string EditorFailedLoadGameFollowingErrors {
            get {
                return ResourceManager.GetString("EditorFailedLoadGameFollowingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load game..
        /// </summary>
        internal static string EditorFailedToLoadGame {
            get {
                return ResourceManager.GetString("EditorFailedToLoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string EditorFilenameNone {
            get {
                return ResourceManager.GetString("EditorFilenameNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string EditorFileNone {
            get {
                return ResourceManager.GetString("EditorFileNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} already exists.{1}Would you like to overwrite it?.
        /// </summary>
        internal static string EditorFileOverwrite {
            get {
                return ResourceManager.GetString("EditorFileOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files can only be created in the game folder..
        /// </summary>
        internal static string EditorFilesOnlyInGameFolder {
            get {
                return ResourceManager.GetString("EditorFilesOnlyInGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |All files|*.*.
        /// </summary>
        internal static string EditorFilterAllFiles {
            get {
                return ResourceManager.GetString("EditorFilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game files|.
        /// </summary>
        internal static string EditorFilterGameFiles {
            get {
                return ResourceManager.GetString("EditorFilterGameFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Games|*.&quot;.
        /// </summary>
        internal static string EditorFilterSavedGames {
            get {
                return ResourceManager.GetString("EditorFilterSavedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Library Elements.
        /// </summary>
        internal static string EditorFilterShowLibraryElements {
            get {
                return ResourceManager.GetString("EditorFilterShowLibraryElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occurred:.
        /// </summary>
        internal static string EditorFollowingErrorsOccurred {
            get {
                return ResourceManager.GetString("EditorFollowingErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From library {0}.
        /// </summary>
        internal static string EditorFromLibrary {
            get {
                return ResourceManager.GetString("EditorFromLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string EditorFromLibraryCopy {
            get {
                return ResourceManager.GetString("EditorFromLibraryCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game file {0} does not exist.{1}Would you like to find the file yourself?.
        /// </summary>
        internal static string EditorGameFileNotExistLikeFind {
            get {
                return ResourceManager.GetString("EditorGameFileNotExistLikeFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate....
        /// </summary>
        internal static string EditorGenerate {
            get {
                return ResourceManager.GetString("EditorGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If.
        /// </summary>
        internal static string EditorIf {
            get {
                return ResourceManager.GetString("EditorIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an image.
        /// </summary>
        internal static string EditorImageSelectionWindowTitle {
            get {
                return ResourceManager.GetString("EditorImageSelectionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid column style.
        /// </summary>
        internal static string EditorInvalidColumnStyle {
            get {
                return ResourceManager.GetString("EditorInvalidColumnStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid control type for expression.
        /// </summary>
        internal static string EditorInvalidControlTypeExpression {
            get {
                return ResourceManager.GetString("EditorInvalidControlTypeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expression.
        /// </summary>
        internal static string EditorInvalidExpression {
            get {
                return ResourceManager.GetString("EditorInvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid save file name. Save file names must end with the extension.
        /// </summary>
        internal static string EditorInvalidSaveFileName {
            get {
                return ResourceManager.GetString("EditorInvalidSaveFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the exit name.
        /// </summary>
        internal static string EditorKeypromptEnterExitName {
            get {
                return ResourceManager.GetString("EditorKeypromptEnterExitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the object name.
        /// </summary>
        internal static string EditorKeypromptEnterObjectName {
            get {
                return ResourceManager.GetString("EditorKeypromptEnterObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string EditorLaunchCaptionPlay {
            get {
                return ResourceManager.GetString("EditorLaunchCaptionPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link text.
        /// </summary>
        internal static string EditorLinkText {
            get {
                return ResourceManager.GetString("EditorLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + add.
        /// </summary>
        internal static string EditorMenuItemAdd {
            get {
                return ResourceManager.GetString("EditorMenuItemAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string EditorMenuItemAnd {
            get {
                return ResourceManager.GetString("EditorMenuItemAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string EditorMenuItemAttribute {
            get {
                return ResourceManager.GetString("EditorMenuItemAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Clear).
        /// </summary>
        internal static string EditorMenuItemClear {
            get {
                return ResourceManager.GetString("EditorMenuItemClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to / divide.
        /// </summary>
        internal static string EditorMenuItemDivide {
            get {
                return ResourceManager.GetString("EditorMenuItemDivide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = equals.
        /// </summary>
        internal static string EditorMenuItemEquals {
            get {
                return ResourceManager.GetString("EditorMenuItemEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string EditorMenuItemFalse {
            get {
                return ResourceManager.GetString("EditorMenuItemFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string EditorMenuItemFunction {
            get {
                return ResourceManager.GetString("EditorMenuItemFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; greater than.
        /// </summary>
        internal static string EditorMenuItemGreaterThan {
            get {
                return ResourceManager.GetString("EditorMenuItemGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; less than.
        /// </summary>
        internal static string EditorMenuItemlessThan {
            get {
                return ResourceManager.GetString("EditorMenuItemlessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * multiply.
        /// </summary>
        internal static string EditorMenuItemMultiply {
            get {
                return ResourceManager.GetString("EditorMenuItemMultiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&gt; not equals.
        /// </summary>
        internal static string EditorMenuItemNotEquals {
            get {
                return ResourceManager.GetString("EditorMenuItemNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string EditorMenuItemObject {
            get {
                return ResourceManager.GetString("EditorMenuItemObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string EditorMenuItemOr {
            get {
                return ResourceManager.GetString("EditorMenuItemOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - subtract.
        /// </summary>
        internal static string EditorMenuItemSubtract {
            get {
                return ResourceManager.GetString("EditorMenuItemSubtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object.
        /// </summary>
        internal static string EditorMenuItemThis {
            get {
                return ResourceManager.GetString("EditorMenuItemThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string EditorMenuItemTrue {
            get {
                return ResourceManager.GetString("EditorMenuItemTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        internal static string EditorMenuItemVariable {
            get {
                return ResourceManager.GetString("EditorMenuItemVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been modified outside Quest..
        /// </summary>
        internal static string EditorModifiedOutside {
            get {
                return ResourceManager.GetString("EditorModifiedOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the new data.
        /// </summary>
        internal static string EditorNewdata {
            get {
                return ResourceManager.GetString("EditorNewdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the new {0}.
        /// </summary>
        internal static string EditorNewElement {
            get {
                return ResourceManager.GetString("EditorNewElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        internal static string EditorNewFileButton {
            get {
                return ResourceManager.GetString("EditorNewFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the new object.
        /// </summary>
        internal static string EditorNewObject {
            get {
                return ResourceManager.GetString("EditorNewObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the new page.
        /// </summary>
        internal static string EditorNewPage {
            get {
                return ResourceManager.GetString("EditorNewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the new room.
        /// </summary>
        internal static string EditorNewRoom {
            get {
                return ResourceManager.GetString("EditorNewRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the new template.
        /// </summary>
        internal static string EditorNewTemplate {
            get {
                return ResourceManager.GetString("EditorNewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the new walkthrough.
        /// </summary>
        internal static string EditorNewWalkthrough {
            get {
                return ResourceManager.GetString("EditorNewWalkthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to look.
        /// </summary>
        internal static string EditorNoLinkDestinationLook {
            get {
                return ResourceManager.GetString("EditorNoLinkDestinationLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string EditorNoLinkDestinationNone {
            get {
                return ResourceManager.GetString("EditorNoLinkDestinationNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not be able to upload this file to textadventures.co.uk..
        /// </summary>
        internal static string EditorNotBeAbleUploadFile {
            get {
                return ResourceManager.GetString("EditorNotBeAbleUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string EditorNotParents {
            get {
                return ResourceManager.GetString("EditorNotParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string EditorOkButton {
            get {
                return ResourceManager.GetString("EditorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file size is over 20 MB. Consider reducing the size of any image or sound files, and delete any unused files from the game folder..
        /// </summary>
        internal static string EditorOutputFileOver {
            get {
                return ResourceManager.GetString("EditorOutputFileOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite the existing .quest file?.
        /// </summary>
        internal static string EditorOverwriteExistingFile {
            get {
                return ResourceManager.GetString("EditorOverwriteExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string EditorParent {
            get {
                return ResourceManager.GetString("EditorParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent element and attribute must be specified to wrap command pattern.
        /// </summary>
        internal static string EditorParentElementSpecifiedCommandPattern {
            get {
                return ResourceManager.GetString("EditorParentElementSpecifiedCommandPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent element and attribute must be specified to wrap object reference.
        /// </summary>
        internal static string EditorParentElementSpecifiedObjectReference {
            get {
                return ResourceManager.GetString("EditorParentElementSpecifiedObjectReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste not implemented for this editor type.
        /// </summary>
        internal static string EditorPasteNotImplementedForThisType {
            get {
                return ResourceManager.GetString("EditorPasteNotImplementedForThisType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Files.
        /// </summary>
        internal static string EditorPictureFiles {
            get {
                return ResourceManager.GetString("EditorPictureFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an object.
        /// </summary>
        internal static string EditorPleaseChooseObject {
            get {
                return ResourceManager.GetString("EditorPleaseChooseObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a key.
        /// </summary>
        internal static string EditorPleaseEnterKey {
            get {
                return ResourceManager.GetString("EditorPleaseEnterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter {0} name.
        /// </summary>
        internal static string EditorPleaseEnterName {
            get {
                return ResourceManager.GetString("EditorPleaseEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an attribute.
        /// </summary>
        internal static string EditorPleaseEnterNameAttribute {
            get {
                return ResourceManager.GetString("EditorPleaseEnterNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a function.
        /// </summary>
        internal static string EditorPleaseEnterNameFunction {
            get {
                return ResourceManager.GetString("EditorPleaseEnterNameFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an object.
        /// </summary>
        internal static string EditorPleaseEnterNameObject {
            get {
                return ResourceManager.GetString("EditorPleaseEnterNameObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a variable.
        /// </summary>
        internal static string EditorPleaseEnterNameVariable {
            get {
                return ResourceManager.GetString("EditorPleaseEnterNameVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value.
        /// </summary>
        internal static string EditorPleaseEnterValue {
            get {
                return ResourceManager.GetString("EditorPleaseEnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print a message.
        /// </summary>
        internal static string EditorPrintMessage {
            get {
                return ResourceManager.GetString("EditorPrintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string EditorReload {
            get {
                return ResourceManager.GetString("EditorReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this item.
        /// </summary>
        internal static string EditorRemoveThisItem {
            get {
                return ResourceManager.GetString("EditorRemoveThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced {0} occurrences..
        /// </summary>
        internal static string EditorReplacedOccurrences {
            get {
                return ResourceManager.GetString("EditorReplacedOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require another object.
        /// </summary>
        internal static string EditorRequireAnotherObject {
            get {
                return ResourceManager.GetString("EditorRequireAnotherObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a script.
        /// </summary>
        internal static string EditorRunScript {
            get {
                return ResourceManager.GetString("EditorRunScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save your changes before closing?.
        /// </summary>
        internal static string EditorSaveBeforeClosing {
            get {
                return ResourceManager.GetString("EditorSaveBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save your changes before editing this game in the code view?.
        /// </summary>
        internal static string EditorSaveBeforeEditingThisGame {
            get {
                return ResourceManager.GetString("EditorSaveBeforeEditingThisGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save your changes before leaving the code view?.
        /// </summary>
        internal static string EditorSaveBeforeLeavingCodeView {
            get {
                return ResourceManager.GetString("EditorSaveBeforeLeavingCodeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save your changes before creating a new game?.
        /// </summary>
        internal static string EditorSaveChangesBeforeCreating {
            get {
                return ResourceManager.GetString("EditorSaveChangesBeforeCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save your changes before opening a new game?.
        /// </summary>
        internal static string EditorSaveChangesBeforeOpening {
            get {
                return ResourceManager.GetString("EditorSaveChangesBeforeOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this game and then click Reload to apply changes from updating Included Libraries..
        /// </summary>
        internal static string EditorSaveGameAndClickReload {
            get {
                return ResourceManager.GetString("EditorSaveGameAndClickReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are editing your game, you must save it from the Editor screen. The Save command in a game is for saving your play progress..
        /// </summary>
        internal static string EditorSaveItFromEditorScreen {
            get {
                return ResourceManager.GetString("EditorSaveItFromEditorScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string EditorScriptAdderAdd {
            get {
                return ResourceManager.GetString("EditorScriptAdderAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string EditorScriptAdderClose {
            get {
                return ResourceManager.GetString("EditorScriptAdderClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Script Command.
        /// </summary>
        internal static string EditorScriptAdderWindowTitle {
            get {
                return ResourceManager.GetString("EditorScriptAdderWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred..
        /// </summary>
        internal static string EditorSorryErrorOccurred {
            get {
                return ResourceManager.GetString("EditorSorryErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text not found: {0}.
        /// </summary>
        internal static string EditorTextNotFound {
            get {
                return ResourceManager.GetString("EditorTextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Processor help.
        /// </summary>
        internal static string EditorTextProcessorHelp {
            get {
                return ResourceManager.GetString("EditorTextProcessorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then.
        /// </summary>
        internal static string EditorThen {
            get {
                return ResourceManager.GetString("EditorThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        internal static string EditorToLabel {
            get {
                return ResourceManager.GetString("EditorToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Script.
        /// </summary>
        internal static string EditorToolBarAddScript {
            get {
                return ResourceManager.GetString("EditorToolBarAddScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code View.
        /// </summary>
        internal static string EditorToolBarCodeView {
            get {
                return ResourceManager.GetString("EditorToolBarCodeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string EditorToolBarCopy {
            get {
                return ResourceManager.GetString("EditorToolBarCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string EditorToolBarCut {
            get {
                return ResourceManager.GetString("EditorToolBarCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string EditorToolBarDelete {
            get {
                return ResourceManager.GetString("EditorToolBarDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make editable copy.
        /// </summary>
        internal static string EditorToolBarMakeEditable {
            get {
                return ResourceManager.GetString("EditorToolBarMakeEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        internal static string EditorToolBarMoveDown {
            get {
                return ResourceManager.GetString("EditorToolBarMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        internal static string EditorToolBarMoveUp {
            get {
                return ResourceManager.GetString("EditorToolBarMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string EditorToolBarPaste {
            get {
                return ResourceManager.GetString("EditorToolBarPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop out.
        /// </summary>
        internal static string EditorToolBarPopOut {
            get {
                return ResourceManager.GetString("EditorToolBarPopOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is already inherited.
        /// </summary>
        internal static string EditorTypAlreadyInherited {
            get {
                return ResourceManager.GetString("EditorTypAlreadyInherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not exist.
        /// </summary>
        internal static string EditorTypNotExists {
            get {
                return ResourceManager.GetString("EditorTypNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add attribute.
        /// </summary>
        internal static string EditorUnableAddAttribute {
            get {
                return ResourceManager.GetString("EditorUnableAddAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy file. The following error occurred:{0}.
        /// </summary>
        internal static string EditorUnableCopyFileErrorOccurred {
            get {
                return ResourceManager.GetString("EditorUnableCopyFileErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create file. The following error occurred:{0}.
        /// </summary>
        internal static string EditorUnableCreateFileErrorOccured {
            get {
                return ResourceManager.GetString("EditorUnableCreateFileErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete file: .
        /// </summary>
        internal static string EditorUnableDeleteFile {
            get {
                return ResourceManager.GetString("EditorUnableDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to publish game.
        /// </summary>
        internal static string EditorUnablePublishGame {
            get {
                return ResourceManager.GetString("EditorUnablePublishGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the file due to the following error:.
        /// </summary>
        internal static string EditorUnableSaveFileError {
            get {
                return ResourceManager.GetString("EditorUnableSaveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set attribute value.
        /// </summary>
        internal static string EditorUnableSetAttributeValue {
            get {
                return ResourceManager.GetString("EditorUnableSetAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add data.
        /// </summary>
        internal static string EditorUnableToAdddata {
            get {
                return ResourceManager.GetString("EditorUnableToAdddata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add element.
        /// </summary>
        internal static string EditorUnableToAddEmement {
            get {
                return ResourceManager.GetString("EditorUnableToAddEmement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add item.
        /// </summary>
        internal static string EditorUnableToAddItem {
            get {
                return ResourceManager.GetString("EditorUnableToAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add page.
        /// </summary>
        internal static string EditorUnableToAddPage {
            get {
                return ResourceManager.GetString("EditorUnableToAddPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add type.
        /// </summary>
        internal static string EditorUnableToAddType {
            get {
                return ResourceManager.GetString("EditorUnableToAddType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add verb.
        /// </summary>
        internal static string EditorUnableToAddVerb {
            get {
                return ResourceManager.GetString("EditorUnableToAddVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the file due to the following error:.
        /// </summary>
        internal static string EditorUnableToSave {
            get {
                return ResourceManager.GetString("EditorUnableToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set &apos;{0}&apos;.
        /// </summary>
        internal static string EditorUnableToSet {
            get {
                return ResourceManager.GetString("EditorUnableToSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled event.
        /// </summary>
        internal static string EditorUnhandledEvent {
            get {
                return ResourceManager.GetString("EditorUnhandledEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown attribute type for DisplayString.
        /// </summary>
        internal static string EditorUnknownAttributeTypeDisplayString {
            get {
                return ResourceManager.GetString("EditorUnknownAttributeTypeDisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown control type.
        /// </summary>
        internal static string EditorUnknownControlType {
            get {
                return ResourceManager.GetString("EditorUnknownControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown dictionary type.
        /// </summary>
        internal static string EditorUnknownDictionaryType {
            get {
                return ResourceManager.GetString("EditorUnknownDictionaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown direction {0}.
        /// </summary>
        internal static string EditorUnknownDirection {
            get {
                return ResourceManager.GetString("EditorUnknownDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown list type.
        /// </summary>
        internal static string EditorUnknownListType {
            get {
                return ResourceManager.GetString("EditorUnknownListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown source list for dropdown.
        /// </summary>
        internal static string EditorUnknownSourceListForDropdown {
            get {
                return ResourceManager.GetString("EditorUnknownSourceListForDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognised &apos;else if&apos; attribute.
        /// </summary>
        internal static string EditorUnrecognisedElseIfAttribute {
            get {
                return ResourceManager.GetString("EditorUnrecognisedElseIfAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognised file type. This game cannot be loaded in Quest..
        /// </summary>
        internal static string EditorUnrecognisedFileType {
            get {
                return ResourceManager.GetString("EditorUnrecognisedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognised &apos;if&apos; attribute.
        /// </summary>
        internal static string EditorUnrecogniseIfAttribute {
            get {
                return ResourceManager.GetString("EditorUnrecogniseIfAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes..
        /// </summary>
        internal static string EditorUnsavedChanges {
            get {
                return ResourceManager.GetString("EditorUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player object cannot be renamed.
        /// </summary>
        internal static string EditorValMsgCannotRenamePlayerElement {
            get {
                return ResourceManager.GetString("EditorValMsgCannotRenamePlayerElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular type reference.
        /// </summary>
        internal static string EditorValMsgCircularTypeReference {
            get {
                return ResourceManager.GetString("EditorValMsgCircularTypeReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element called &apos;{0}&apos; already exists in this game.
        /// </summary>
        internal static string EditorValMsgElementAlreadyExists {
            get {
                return ResourceManager.GetString("EditorValMsgElementAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attribute name.
        /// </summary>
        internal static string EditorValMsgInvalidAttributeName1 {
            get {
                return ResourceManager.GetString("EditorValMsgInvalidAttributeName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {1}.
        /// </summary>
        internal static string EditorValMsgInvalidAttributeName2 {
            get {
                return ResourceManager.GetString("EditorValMsgInvalidAttributeName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid element name.
        /// </summary>
        internal static string EditorValMsgInvalidElementName {
            get {
                return ResourceManager.GetString("EditorValMsgInvalidElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid element name. Elements cannot contain these words: .
        /// </summary>
        internal static string EditorValMsgInvalidElementNameInvalidWord {
            get {
                return ResourceManager.GetString("EditorValMsgInvalidElementNameInvalidWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid element name. An element name cannot start or end with a space, and cannot contain multiple consecutive spaces..
        /// </summary>
        internal static string EditorValMsgInvalidElementNameMultipleSpaces {
            get {
                return ResourceManager.GetString("EditorValMsgInvalidElementNameMultipleSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid element name. An element name cannot start with a number..
        /// </summary>
        internal static string EditorValMsgInvalidElementNameStartsWithNumber {
            get {
                return ResourceManager.GetString("EditorValMsgInvalidElementNameStartsWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item &apos;{0}&apos; already exists in the list.
        /// </summary>
        internal static string EditorValMsgItemAlreadyExists {
            get {
                return ResourceManager.GetString("EditorValMsgItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of opening brackets \&quot;(\&quot; does not match the number of closing brackets \&quot;)\&quot;..
        /// </summary>
        internal static string EditorValMsgMismatchingBrackets {
            get {
                return ResourceManager.GetString("EditorValMsgMismatchingBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing quote character (\&quot;).
        /// </summary>
        internal static string EditorValMsgMismatchingQuotes {
            get {
                return ResourceManager.GetString("EditorValMsgMismatchingQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error.
        /// </summary>
        internal static string EditorValMsgOK {
            get {
                return ResourceManager.GetString("EditorValMsgOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verb would clash with command: .
        /// </summary>
        internal static string EditorVerbWithCommand {
            get {
                return ResourceManager.GetString("EditorVerbWithCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex search.
        /// </summary>
        internal static string FindControlchkBoxRegex {
            get {
                return ResourceManager.GetString("FindControlchkBoxRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string FindControlcmdClose {
            get {
                return ResourceManager.GetString("FindControlcmdClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next.
        /// </summary>
        internal static string FindControlcmdFind {
            get {
                return ResourceManager.GetString("FindControlcmdFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string FindControlcmdReplace {
            get {
                return ResourceManager.GetString("FindControlcmdReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        internal static string FindControlcmdReplaceAll {
            get {
                return ResourceManager.GetString("FindControlcmdReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find:.
        /// </summary>
        internal static string FindControllblFind {
            get {
                return ResourceManager.GetString("FindControllblFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with:.
        /// </summary>
        internal static string FindControllblReplace {
            get {
                return ResourceManager.GetString("FindControllblReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string LauncherCancel {
            get {
                return ResourceManager.GetString("LauncherCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to update.
        /// </summary>
        internal static string LauncherClickHereToUpdate {
            get {
                return ResourceManager.GetString("LauncherClickHereToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string LauncherCreate {
            get {
                return ResourceManager.GetString("LauncherCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new game.
        /// </summary>
        internal static string LauncherCreateNewGame {
            get {
                return ResourceManager.GetString("LauncherCreateNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string LauncherDownload {
            get {
                return ResourceManager.GetString("LauncherDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete.
        /// </summary>
        internal static string LauncherDownloadComplete {
            get {
                return ResourceManager.GetString("LauncherDownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string LauncherDownloading {
            get {
                return ResourceManager.GetString("LauncherDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string LauncherEdit {
            get {
                return ResourceManager.GetString("LauncherEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Games.
        /// </summary>
        internal static string LauncherGetGames {
            get {
                return ResourceManager.GetString("LauncherGetGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get help in the forums.
        /// </summary>
        internal static string LauncherGetHelpInForums {
            get {
                return ResourceManager.GetString("LauncherGetHelpInForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        internal static string LauncherNewVersion {
            get {
                return ResourceManager.GetString("LauncherNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reviews or comments.
        /// </summary>
        internal static string LauncherNoReviewsOrComments {
            get {
                return ResourceManager.GetString("LauncherNoReviewsOrComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not downloaded.
        /// </summary>
        internal static string LauncherNotDownloaded {
            get {
                return ResourceManager.GetString("LauncherNotDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an existing game.
        /// </summary>
        internal static string LauncherOpenExistingGame {
            get {
                return ResourceManager.GetString("LauncherOpenExistingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string LauncherPlay {
            get {
                return ResourceManager.GetString("LauncherPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the Tutorial.
        /// </summary>
        internal static string LauncherReadTutorial {
            get {
                return ResourceManager.GetString("LauncherReadTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        internal static string LauncherRecent {
            get {
                return ResourceManager.GetString("LauncherRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews and comments.
        /// </summary>
        internal static string LauncherReviewsAndComments {
            get {
                return ResourceManager.GetString("LauncherReviewsAndComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print a message.
        /// </summary>
        internal static string TypePrintMessage {
            get {
                return ResourceManager.GetString("TypePrintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require another object.
        /// </summary>
        internal static string TypeRequireAnotherObject {
            get {
                return ResourceManager.GetString("TypeRequireAnotherObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run script.
        /// </summary>
        internal static string TypeRunScript {
            get {
                return ResourceManager.GetString("TypeRunScript", resourceCulture);
            }
        }
    }
}
