// GENERATED FILE - do not edit by hand.
// Regenerate with: node site/scripts/build-docs-index.mjs
//
// Maps a script editor keyword (<appliesto> in src/Engine/Core/CoreEditor*.aslx)
// to the documentation page and anchor describing it. See that script for how
// entries are derived and why a few keywords are deliberately absent.

export interface DocsIndexEntry {
    /** Site-relative path, including the anchor. */
    path: string;
    /** Same-named function on the gamebook page, when one exists. */
    gamebookPath?: string;
}

export const DOCS_INDEX: Readonly<Record<string, DocsIndexEntry>> = {
    "()": { path: "/howto/tasks/about-functions/#using-functions" },
    "(function)AddPageLink": { path: "/reference/functions/user-interface/#addpagelink", gamebookPath: "/reference/functions/gamebook/#addpagelink" },
    "(function)AddToInventory": { path: "/reference/functions/core/#addtoinventory" },
    "(function)Ask": { path: "/reference/functions/user-interface/#ask" },
    "(function)ChangeCounter": { path: "/reference/functions/gamebook/#changecounter" },
    "(function)ChangePOV": { path: "/reference/functions/core/#changepov" },
    "(function)ClearFramePicture": { path: "/reference/functions/user-interface/#clearframepicture" },
    "(function)ClearScreen": { path: "/reference/functions/user-interface/#clearscreen" },
    "(function)CloneObject": { path: "/reference/functions/objects/#cloneobject" },
    "(function)CloneObjectAndMove": { path: "/reference/functions/objects/#cloneobjectandmove" },
    "(function)DecreaseCounter": { path: "/reference/functions/gamebook/#decreasecounter" },
    "(function)DecreaseHealth": { path: "/reference/functions/attributes/#decreasehealth" },
    "(function)DecreaseMoney": { path: "/reference/functions/attributes/#decreasemoney" },
    "(function)DecreaseObjectCounter": { path: "/reference/functions/attributes/#decreaseobjectcounter" },
    "(function)DecreaseScore": { path: "/reference/functions/attributes/#decreasescore" },
    "(function)DisableTimer": { path: "/reference/functions/timers-turnscripts/#disabletimer" },
    "(function)DisableTurnScript": { path: "/reference/functions/timers-turnscripts/#disableturnscript" },
    "(function)DisplayHttpLink": { path: "/reference/functions/internal-core/#displayhttplink" },
    "(function)DisplayList": { path: "/reference/functions/user-interface/#displaylist" },
    "(function)DisplayMailtoLink": { path: "/reference/functions/user-interface/#displaymailtolink" },
    "(function)EnableTimer": { path: "/reference/functions/timers-turnscripts/#enabletimer" },
    "(function)EnableTurnScript": { path: "/reference/functions/timers-turnscripts/#enableturnscript" },
    "(function)GetInput": { path: "/reference/functions/user-interface/#getinput" },
    "(function)Grid_AddNewShapePoint": { path: "/reference/functions/internal-core/#grid_addnewshapepoint" },
    "(function)Grid_ClearCustomLayer": { path: "/reference/functions/internal-core/#grid_clearcustomlayer" },
    "(function)Grid_DrawArrow": { path: "/reference/functions/internal-core/#grid_drawarrow" },
    "(function)Grid_DrawGridLines": { path: "/reference/functions/internal-core/#grid_drawgridlines" },
    "(function)Grid_DrawImage": { path: "/reference/functions/internal-core/#grid_drawimage" },
    "(function)Grid_DrawLine": { path: "/reference/functions/internal-core/#grid_drawline" },
    "(function)Grid_DrawShape": { path: "/reference/functions/internal-core/#grid_drawshape" },
    "(function)Grid_DrawSquare": { path: "/reference/functions/internal-core/#grid_drawsquare" },
    "(function)Grid_DrawSvg": { path: "/reference/functions/internal-core/#grid_drawsvg" },
    "(function)Grid_LoadSvg": { path: "/reference/functions/internal-core/#grid_loadsvg" },
    "(function)Grid_SetCentre": { path: "/reference/functions/internal-core/#grid_setcentre" },
    "(function)Grid_ShowCustomLayer": { path: "/reference/functions/internal-core/#grid_showcustomlayer" },
    "(function)HelperCloseObject": { path: "/reference/functions/core/#helpercloseobject" },
    "(function)HelperOpenObject": { path: "/reference/functions/core/#helperopenobject" },
    "(function)HidePreviousTurnOutput": { path: "/reference/functions/internal-core/#hidepreviousturnoutput" },
    "(function)IncreaseCounter": { path: "/reference/functions/gamebook/#increasecounter" },
    "(function)IncreaseHealth": { path: "/reference/functions/attributes/#increasehealth" },
    "(function)IncreaseMoney": { path: "/reference/functions/attributes/#increasemoney" },
    "(function)IncreaseObjectCounter": { path: "/reference/functions/attributes/#increaseobjectcounter" },
    "(function)IncreaseScore": { path: "/reference/functions/attributes/#increasescore" },
    "(function)LockExit": { path: "/reference/functions/objects/#lockexit" },
    "(function)Log": { path: "/reference/functions/general/#log" },
    "(function)MakeExitInvisible": { path: "/reference/functions/objects/#makeexitinvisible" },
    "(function)MakeExitVisible": { path: "/reference/functions/objects/#makeexitvisible" },
    "(function)MakeObjectInvisible": { path: "/reference/functions/objects/#makeobjectinvisible" },
    "(function)MakeObjectVisible": { path: "/reference/functions/objects/#makeobjectvisible" },
    "(function)MoveObject": { path: "/reference/functions/objects/#moveobject" },
    "(function)MoveObjectHere": { path: "/reference/functions/core/#moveobjecthere" },
    "(function)MovePlayer": { path: "/reference/functions/gamebook/#moveplayer" },
    "(function)OutputTextNoBr": { path: "/reference/functions/user-interface/#outputtextnobr" },
    "(function)Pause": { path: "/reference/functions/timers-turnscripts/#pause" },
    "(function)PrintCentered": { path: "/reference/functions/user-interface/#printcentered" },
    "(function)RemoveObject": { path: "/reference/functions/objects/#removeobject" },
    "(function)RemovePageLink": { path: "/reference/functions/user-interface/#removepagelink", gamebookPath: "/reference/functions/gamebook/#removepagelink" },
    "(function)SetBackgroundColour": { path: "/reference/functions/user-interface/#setbackgroundcolour" },
    "(function)SetCounter": { path: "/reference/functions/gamebook/#setcounter" },
    "(function)SetDark": { path: "/reference/functions/core/#setdark" },
    "(function)SetExitLightstrength": { path: "/reference/functions/core/#setexitlightstrength" },
    "(function)SetFlagOff": { path: "/reference/functions/gamebook/#setflagoff" },
    "(function)SetFlagOn": { path: "/reference/functions/gamebook/#setflagon" },
    "(function)SetFontName": { path: "/reference/functions/user-interface/#setfontname" },
    "(function)SetFontSize": { path: "/reference/functions/user-interface/#setfontsize" },
    "(function)SetForegroundColour": { path: "/reference/functions/user-interface/#setforegroundcolour" },
    "(function)SetFramePicture": { path: "/reference/functions/user-interface/#setframepicture" },
    "(function)SetLight": { path: "/reference/functions/core/#setlight" },
    "(function)SetObjectFlagOff": { path: "/reference/functions/attributes/#setobjectflagoff" },
    "(function)SetObjectFlagOn": { path: "/reference/functions/attributes/#setobjectflagon" },
    "(function)SetObjectLightstrength": { path: "/reference/functions/core/#setobjectlightstrength" },
    "(function)SetTimeout": { path: "/reference/functions/timers-turnscripts/#settimeout" },
    "(function)SetTimeoutID": { path: "/reference/functions/timers-turnscripts/#settimeoutid" },
    "(function)SetTimerInterval": { path: "/reference/functions/timers-turnscripts/#settimerinterval" },
    "(function)SetTimerScript": { path: "/reference/functions/timers-turnscripts/#settimerscript" },
    "(function)SetTurnScript": { path: "/reference/functions/timers-turnscripts/#setturnscript" },
    "(function)SetTurnTimeout": { path: "/reference/functions/timers-turnscripts/#setturntimeout" },
    "(function)SetTurnTimeoutID": { path: "/reference/functions/timers-turnscripts/#setturntimeoutid" },
    "(function)SetWebFontName": { path: "/reference/functions/user-interface/#setwebfontname" },
    "(function)ShowMenu": { path: "/reference/functions/user-interface/#showmenu" },
    "(function)ShowPage": { path: "/reference/functions/user-interface/#showpage" },
    "(function)ShowYouTube": { path: "/reference/functions/user-interface/#showyoutube" },
    "(function)SuppressTurnscripts": { path: "/reference/functions/timers-turnscripts/#suppressturnscripts" },
    "(function)SwitchOff": { path: "/reference/functions/core/#switchoff" },
    "(function)SwitchOn": { path: "/reference/functions/core/#switchon" },
    "(function)TextFX_Typewriter": { path: "/reference/functions/user-interface/#textfx_typewriter" },
    "(function)TextFX_Unscramble": { path: "/reference/functions/user-interface/#textfx_unscramble" },
    "(function)UnlockExit": { path: "/reference/functions/objects/#unlockexit" },
    "(function)WaitForKeyPress": { path: "/reference/functions/user-interface/#waitforkeypress" },
    "//": { path: "/reference/script-commands/#comments" },
    "=": { path: "/reference/script-commands/#setting-variables" },
    "=>": { path: "/reference/script-commands/#setting-variables" },
    "JS.": { path: "/reference/js/#calling-js-functions" },
    "ask": { path: "/reference/script-commands/#ask" },
    "create": { path: "/reference/script-commands/#create" },
    "create exit": { path: "/reference/script-commands/#create-exit" },
    "create timer": { path: "/reference/script-commands/#create-timer" },
    "create turnscript": { path: "/reference/script-commands/#create-turnscript" },
    "destroy": { path: "/reference/script-commands/#destroy" },
    "dictionary add": { path: "/reference/script-commands/#dictionary-add" },
    "dictionary remove": { path: "/reference/script-commands/#dictionary-remove" },
    "do": { path: "/reference/script-commands/#do" },
    "dynamictemplate": { path: "/reference/functions/string/#dynamictemplate" },
    "error": { path: "/reference/script-commands/#error" },
    "finish": { path: "/reference/script-commands/#finish" },
    "firsttime": { path: "/reference/script-commands/#firsttime" },
    "for": { path: "/reference/script-commands/#for" },
    "foreach": { path: "/reference/script-commands/#foreach" },
    "get input": { path: "/reference/script-commands/#get-input" },
    "if": { path: "/reference/script-commands/#if" },
    "insert": { path: "/reference/script-commands/#insert" },
    "invoke": { path: "/reference/script-commands/#invoke" },
    "list add": { path: "/reference/script-commands/#list-add" },
    "list remove": { path: "/reference/script-commands/#list-remove" },
    "msg": { path: "/reference/script-commands/#msg" },
    "on ready": { path: "/reference/script-commands/#on-ready" },
    "picture": { path: "/reference/script-commands/#picture" },
    "play sound": { path: "/reference/script-commands/#play-sound" },
    "request": { path: "/reference/script-commands/#request" },
    "return": { path: "/reference/script-commands/#return" },
    "rundelegate": { path: "/reference/script-commands/#rundelegate" },
    "set": { path: "/reference/script-commands/#set" },
    "show menu": { path: "/reference/script-commands/#show-menu" },
    "start transaction": { path: "/reference/script-commands/#start-transaction" },
    "stop sound": { path: "/reference/script-commands/#stop-sound" },
    "switch": { path: "/reference/script-commands/#switch" },
    "template": { path: "/reference/functions/string/#template" },
    "undo": { path: "/reference/script-commands/#undo" },
    "wait": { path: "/reference/script-commands/#wait" },
    "while": { path: "/reference/script-commands/#while" },
};

/** Documentation path (as used in a <helpurl>) -> that page's title. */
export const HELP_PAGE_TITLES: Readonly<Record<string, string>> = {
    "/customise/look-and-feel/#the-display-tab": "The Display tab",
    "/customise/look-and-feel/#the-interface-tab": "The Interface tab",
    "/customise/look-and-feel/#the-room-descriptions-tab": "The Room Descriptions tab",
    "/customise/object-verbs/": "Object verbs",
    "/howto/characters/ask-tell/": "Building an Ask/Tell system",
    "/howto/characters/pages/": "Building a conversation with Pages",
    "/howto/commands/how-commands-work/": "How commands work",
    "/howto/commands/verbs/": "Verbs",
    "/howto/objects/clothing/": "Wearable items",
    "/howto/objects/containers/": "Containers and surfaces",
    "/howto/objects/features/#annotations": "Annotations",
    "/howto/objects/features/#game-features": "Game features",
    "/howto/objects/features/#object-features": "Object features",
    "/howto/objects/food/": "Items that can be eaten",
    "/howto/objects/switchable/": "Items that can be switched on and off",
    "/howto/objects/taking-and-dropping/": "Taking and dropping objects",
    "/howto/player/player-object/": "Changing the player object",
    "/howto/rooms/exits/": "Exits",
    "/howto/rooms/light-and-darkness/": "Handling light and dark",
    "/howto/rooms/map/": "Showing a map",
    "/howto/rooms/objects-and-rooms/#the-objects-tab": "The Objects tab",
    "/howto/rooms/objects-and-rooms/#the-room-tab": "The Room tab",
    "/howto/rooms/objects-and-rooms/#the-setup-tab": "The Setup tab",
    "/howto/scripting/advanced-game-scripts/": "Advanced game scripts",
    "/howto/time/time-turns-and-timers/": "Time, turns and timers",
    "/publishing/game-details/": "Your game's details",
    "/tutorial/creating-a-gamebook/": "Creating a gamebook",
    "/tutorial/custom-attributes/#the-attributes-tab": "The attributes tab",
    "/tutorial/more-things-to-do-with-objects/": "More things to do with objects",
    "/tutorial/turns-and-timers/#real-time-timers": "Real-time timers",
    "/understanding/when-scripts-run/#object-initialisation-scripts": "Object initialisation scripts",
    "/understanding/when-scripts-run/#the-game-scripts-tab": "The game Scripts tab",
    "/understanding/when-scripts-run/#the-room-scripts-tab": "The room Scripts tab",
};
