<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Library</OutputType>
        <RootNamespace>QuestViva.EditorCore</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>default</LangVersion>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>
    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>
    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>EditorCoreTests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Common\Common.csproj" />
        <ProjectReference Include="..\Engine\Engine.csproj" />
    </ItemGroup>

</Project>