//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextAdventures.Utility.Language {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextAdventures.Utility.Language.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Else ähnelt.
        /// </summary>
        internal static string EditorAddElse {
            get {
                return ResourceManager.GetString("EditorAddElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Else If ähnelt.
        /// </summary>
        internal static string EditorAddElseIf {
            get {
                return ResourceManager.GetString("EditorAddElseIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add link to ähnelt.
        /// </summary>
        internal static string EditorAddLinkTo {
            get {
                return ResourceManager.GetString("EditorAddLinkTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse... ähnelt.
        /// </summary>
        internal static string EditorBrowseButton {
            get {
                return ResourceManager.GetString("EditorBrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quest Games (*.aslx)|*.aslx|All files|*.* ähnelt.
        /// </summary>
        internal static string EditorBrowseEditFilter {
            get {
                return ResourceManager.GetString("EditorBrowseEditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quest Games|*.quest;*.quest-save;*.aslx;*.asl;*.cas;*.qsg|All files|*.* ähnelt.
        /// </summary>
        internal static string EditorBrowseFilter {
            get {
                return ResourceManager.GetString("EditorBrowseFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string EditorCancelButton {
            get {
                return ResourceManager.GetString("EditorCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot mix element types in the clipboard ähnelt.
        /// </summary>
        internal static string EditorCannotMixElementTypesInClipboard {
            get {
                return ResourceManager.GetString("EditorCannotMixElementTypesInClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t play sound that is both synchronous and looped ähnelt.
        /// </summary>
        internal static string EditorCantPlaySound {
            get {
                return ResourceManager.GetString("EditorCantPlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To change the language, Quest must be restarted. Would you like to continue? ähnelt.
        /// </summary>
        internal static string EditorChangeLangRestartContinue {
            get {
                return ResourceManager.GetString("EditorChangeLangRestartContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Also create exit in the other direction ähnelt.
        /// </summary>
        internal static string EditorChkCorresponding {
            get {
                return ResourceManager.GetString("EditorChkCorresponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please choose a walkthrough to run: ähnelt.
        /// </summary>
        internal static string EditorChooseAWalktroughToRun {
            get {
                return ResourceManager.GetString("EditorChooseAWalktroughToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please choose a type to add ähnelt.
        /// </summary>
        internal static string EditorChooseTypeToAdd {
            get {
                return ResourceManager.GetString("EditorChooseTypeToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear all items ähnelt.
        /// </summary>
        internal static string EditorClearAllItems {
            get {
                return ResourceManager.GetString("EditorClearAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        internal static string EditorCmdDelete {
            get {
                return ResourceManager.GetString("EditorCmdDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit in the other direction already exists ähnelt.
        /// </summary>
        internal static string EditorCorresponding {
            get {
                return ResourceManager.GetString("EditorCorresponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create exit ähnelt.
        /// </summary>
        internal static string EditorCreate {
            get {
                return ResourceManager.GetString("EditorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create exit in the other direction ähnelt.
        /// </summary>
        internal static string EditorCreateCorresponding {
            get {
                return ResourceManager.GetString("EditorCreateCorresponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create an exit: ähnelt.
        /// </summary>
        internal static string EditorCreateExitTitle {
            get {
                return ResourceManager.GetString("EditorCreateExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create local copy of &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string EditorCreateLocalCopy {
            get {
                return ResourceManager.GetString("EditorCreateLocalCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create &quot;look&quot; direction ähnelt.
        /// </summary>
        internal static string EditorCreateLookOnly {
            get {
                return ResourceManager.GetString("EditorCreateLookOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allows players to look in this direction, but not move this way. ähnelt.
        /// </summary>
        internal static string EditorCreateLookOnlyDesc {
            get {
                return ResourceManager.GetString("EditorCreateLookOnlyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Or create a &quot;look&quot; direction: ähnelt.
        /// </summary>
        internal static string EditorCreateLookOnlyTitle {
            get {
                return ResourceManager.GetString("EditorCreateLookOnlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete downloaded file ähnelt.
        /// </summary>
        internal static string EditorDeleteDownloadedFile {
            get {
                return ResourceManager.GetString("EditorDeleteDownloadedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A different file called {0} already exists in the game folder.\n\nWould you like to overwrite it? ähnelt.
        /// </summary>
        internal static string EditorDifferentFileOverrideIt {
            get {
                return ResourceManager.GetString("EditorDifferentFileOverrideIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No exit selected ähnelt.
        /// </summary>
        internal static string EditorDirectionNoSelect {
            get {
                return ResourceManager.GetString("EditorDirectionNoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected exit is not a compass direction ähnelt.
        /// </summary>
        internal static string EditorDirectionSelect {
            get {
                return ResourceManager.GetString("EditorDirectionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string EditorEdit {
            get {
                return ResourceManager.GetString("EditorEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Element is not defined in a library ähnelt.
        /// </summary>
        internal static string EditorElementIsNotDefinedInLibrary {
            get {
                return ResourceManager.GetString("EditorElementIsNotDefinedInLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Else ähnelt.
        /// </summary>
        internal static string EditorElse {
            get {
                return ResourceManager.GetString("EditorElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Else If ähnelt.
        /// </summary>
        internal static string EditorElseIf {
            get {
                return ResourceManager.GetString("EditorElseIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a name for the new attribute ähnelt.
        /// </summary>
        internal static string EditorEnterNameAttribute {
            get {
                return ResourceManager.GetString("EditorEnterNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a name for the new verb ähnelt.
        /// </summary>
        internal static string EditorEnterNameForNewVerb {
            get {
                return ResourceManager.GetString("EditorEnterNameForNewVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error running command ähnelt.
        /// </summary>
        internal static string EditorErrorRunningCommand {
            get {
                return ResourceManager.GetString("EditorErrorRunningCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error - walkthrough halted: ähnelt.
        /// </summary>
        internal static string EditorErrorWalkthroughHalted {
            get {
                return ResourceManager.GetString("EditorErrorWalkthroughHalted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to create folder:  ähnelt.
        /// </summary>
        internal static string EditorFailedCreateFolder {
            get {
                return ResourceManager.GetString("EditorFailedCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to load game due to the following errors: ähnelt.
        /// </summary>
        internal static string EditorFailedLoadGameFollowingErrors {
            get {
                return ResourceManager.GetString("EditorFailedLoadGameFollowingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to load game. ähnelt.
        /// </summary>
        internal static string EditorFailedToLoadGame {
            get {
                return ResourceManager.GetString("EditorFailedToLoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string EditorFilenameNone {
            get {
                return ResourceManager.GetString("EditorFilenameNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string EditorFileNone {
            get {
                return ResourceManager.GetString("EditorFileNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file {0} already exists.{1}Would you like to overwrite it? ähnelt.
        /// </summary>
        internal static string EditorFileOverwrite {
            get {
                return ResourceManager.GetString("EditorFileOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Files can only be created in the game folder. ähnelt.
        /// </summary>
        internal static string EditorFilesOnlyInGameFolder {
            get {
                return ResourceManager.GetString("EditorFilesOnlyInGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die |All files|*.* ähnelt.
        /// </summary>
        internal static string EditorFilterAllFiles {
            get {
                return ResourceManager.GetString("EditorFilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game files| ähnelt.
        /// </summary>
        internal static string EditorFilterGameFiles {
            get {
                return ResourceManager.GetString("EditorFilterGameFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saved Games|*.&quot; ähnelt.
        /// </summary>
        internal static string EditorFilterSavedGames {
            get {
                return ResourceManager.GetString("EditorFilterSavedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Library Elements ähnelt.
        /// </summary>
        internal static string EditorFilterShowLibraryElements {
            get {
                return ResourceManager.GetString("EditorFilterShowLibraryElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following errors occurred: ähnelt.
        /// </summary>
        internal static string EditorFollowingErrorsOccurred {
            get {
                return ResourceManager.GetString("EditorFollowingErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From library {0} ähnelt.
        /// </summary>
        internal static string EditorFromLibrary {
            get {
                return ResourceManager.GetString("EditorFromLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        internal static string EditorFromLibraryCopy {
            get {
                return ResourceManager.GetString("EditorFromLibraryCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The game file {0} does not exist.{1}Would you like to find the file yourself? ähnelt.
        /// </summary>
        internal static string EditorGameFileNotExistLikeFind {
            get {
                return ResourceManager.GetString("EditorGameFileNotExistLikeFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate... ähnelt.
        /// </summary>
        internal static string EditorGenerate {
            get {
                return ResourceManager.GetString("EditorGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If ähnelt.
        /// </summary>
        internal static string EditorIf {
            get {
                return ResourceManager.GetString("EditorIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose an image ähnelt.
        /// </summary>
        internal static string EditorImageSelectionWindowTitle {
            get {
                return ResourceManager.GetString("EditorImageSelectionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid column style ähnelt.
        /// </summary>
        internal static string EditorInvalidColumnStyle {
            get {
                return ResourceManager.GetString("EditorInvalidColumnStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid control type for expression ähnelt.
        /// </summary>
        internal static string EditorInvalidControlTypeExpression {
            get {
                return ResourceManager.GetString("EditorInvalidControlTypeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid expression ähnelt.
        /// </summary>
        internal static string EditorInvalidExpression {
            get {
                return ResourceManager.GetString("EditorInvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid save file name. Save file names must end with the extension ähnelt.
        /// </summary>
        internal static string EditorInvalidSaveFileName {
            get {
                return ResourceManager.GetString("EditorInvalidSaveFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the exit name ähnelt.
        /// </summary>
        internal static string EditorKeypromptEnterExitName {
            get {
                return ResourceManager.GetString("EditorKeypromptEnterExitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the object name ähnelt.
        /// </summary>
        internal static string EditorKeypromptEnterObjectName {
            get {
                return ResourceManager.GetString("EditorKeypromptEnterObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play ähnelt.
        /// </summary>
        internal static string EditorLaunchCaptionPlay {
            get {
                return ResourceManager.GetString("EditorLaunchCaptionPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link text ähnelt.
        /// </summary>
        internal static string EditorLinkText {
            get {
                return ResourceManager.GetString("EditorLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die + add ähnelt.
        /// </summary>
        internal static string EditorMenuItemAdd {
            get {
                return ResourceManager.GetString("EditorMenuItemAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and ähnelt.
        /// </summary>
        internal static string EditorMenuItemAnd {
            get {
                return ResourceManager.GetString("EditorMenuItemAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attribute ähnelt.
        /// </summary>
        internal static string EditorMenuItemAttribute {
            get {
                return ResourceManager.GetString("EditorMenuItemAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Clear) ähnelt.
        /// </summary>
        internal static string EditorMenuItemClear {
            get {
                return ResourceManager.GetString("EditorMenuItemClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die / divide ähnelt.
        /// </summary>
        internal static string EditorMenuItemDivide {
            get {
                return ResourceManager.GetString("EditorMenuItemDivide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die = equals ähnelt.
        /// </summary>
        internal static string EditorMenuItemEquals {
            get {
                return ResourceManager.GetString("EditorMenuItemEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die False ähnelt.
        /// </summary>
        internal static string EditorMenuItemFalse {
            get {
                return ResourceManager.GetString("EditorMenuItemFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Function ähnelt.
        /// </summary>
        internal static string EditorMenuItemFunction {
            get {
                return ResourceManager.GetString("EditorMenuItemFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &gt; greater than ähnelt.
        /// </summary>
        internal static string EditorMenuItemGreaterThan {
            get {
                return ResourceManager.GetString("EditorMenuItemGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt; less than ähnelt.
        /// </summary>
        internal static string EditorMenuItemlessThan {
            get {
                return ResourceManager.GetString("EditorMenuItemlessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die * multiply ähnelt.
        /// </summary>
        internal static string EditorMenuItemMultiply {
            get {
                return ResourceManager.GetString("EditorMenuItemMultiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;&gt; not equals ähnelt.
        /// </summary>
        internal static string EditorMenuItemNotEquals {
            get {
                return ResourceManager.GetString("EditorMenuItemNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Object ähnelt.
        /// </summary>
        internal static string EditorMenuItemObject {
            get {
                return ResourceManager.GetString("EditorMenuItemObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die or ähnelt.
        /// </summary>
        internal static string EditorMenuItemOr {
            get {
                return ResourceManager.GetString("EditorMenuItemOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - subtract ähnelt.
        /// </summary>
        internal static string EditorMenuItemSubtract {
            get {
                return ResourceManager.GetString("EditorMenuItemSubtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This object ähnelt.
        /// </summary>
        internal static string EditorMenuItemThis {
            get {
                return ResourceManager.GetString("EditorMenuItemThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die True ähnelt.
        /// </summary>
        internal static string EditorMenuItemTrue {
            get {
                return ResourceManager.GetString("EditorMenuItemTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Variable ähnelt.
        /// </summary>
        internal static string EditorMenuItemVariable {
            get {
                return ResourceManager.GetString("EditorMenuItemVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} has been modified outside Quest. ähnelt.
        /// </summary>
        internal static string EditorModifiedOutside {
            get {
                return ResourceManager.GetString("EditorModifiedOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a name for the new data ähnelt.
        /// </summary>
        internal static string EditorNewdata {
            get {
                return ResourceManager.GetString("EditorNewdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a name for the new {0} ähnelt.
        /// </summary>
        internal static string EditorNewElement {
            get {
                return ResourceManager.GetString("EditorNewElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New... ähnelt.
        /// </summary>
        internal static string EditorNewFileButton {
            get {
                return ResourceManager.GetString("EditorNewFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a name for the new object ähnelt.
        /// </summary>
        internal static string EditorNewObject {
            get {
                return ResourceManager.GetString("EditorNewObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a name for the new page ähnelt.
        /// </summary>
        internal static string EditorNewPage {
            get {
                return ResourceManager.GetString("EditorNewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a name for the new room ähnelt.
        /// </summary>
        internal static string EditorNewRoom {
            get {
                return ResourceManager.GetString("EditorNewRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a name for the new template ähnelt.
        /// </summary>
        internal static string EditorNewTemplate {
            get {
                return ResourceManager.GetString("EditorNewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a name for the new walkthrough ähnelt.
        /// </summary>
        internal static string EditorNewWalkthrough {
            get {
                return ResourceManager.GetString("EditorNewWalkthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die look ähnelt.
        /// </summary>
        internal static string EditorNoLinkDestinationLook {
            get {
                return ResourceManager.GetString("EditorNoLinkDestinationLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (none) ähnelt.
        /// </summary>
        internal static string EditorNoLinkDestinationNone {
            get {
                return ResourceManager.GetString("EditorNoLinkDestinationNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You may not be able to upload this file to textadventures.co.uk. ähnelt.
        /// </summary>
        internal static string EditorNotBeAbleUploadFile {
            get {
                return ResourceManager.GetString("EditorNotBeAbleUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (none) ähnelt.
        /// </summary>
        internal static string EditorNotParents {
            get {
                return ResourceManager.GetString("EditorNotParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string EditorOkButton {
            get {
                return ResourceManager.GetString("EditorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output file size is over 20 MB. Consider reducing the size of any image or sound files, and delete any unused files from the game folder. ähnelt.
        /// </summary>
        internal static string EditorOutputFileOver {
            get {
                return ResourceManager.GetString("EditorOutputFileOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to overwrite the existing .quest file? ähnelt.
        /// </summary>
        internal static string EditorOverwriteExistingFile {
            get {
                return ResourceManager.GetString("EditorOverwriteExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parent ähnelt.
        /// </summary>
        internal static string EditorParent {
            get {
                return ResourceManager.GetString("EditorParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parent element and attribute must be specified to wrap command pattern ähnelt.
        /// </summary>
        internal static string EditorParentElementSpecifiedCommandPattern {
            get {
                return ResourceManager.GetString("EditorParentElementSpecifiedCommandPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parent element and attribute must be specified to wrap object reference ähnelt.
        /// </summary>
        internal static string EditorParentElementSpecifiedObjectReference {
            get {
                return ResourceManager.GetString("EditorParentElementSpecifiedObjectReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste not implemented for this editor type ähnelt.
        /// </summary>
        internal static string EditorPasteNotImplementedForThisType {
            get {
                return ResourceManager.GetString("EditorPasteNotImplementedForThisType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Picture Files ähnelt.
        /// </summary>
        internal static string EditorPictureFiles {
            get {
                return ResourceManager.GetString("EditorPictureFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please choose an object ähnelt.
        /// </summary>
        internal static string EditorPleaseChooseObject {
            get {
                return ResourceManager.GetString("EditorPleaseChooseObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a key ähnelt.
        /// </summary>
        internal static string EditorPleaseEnterKey {
            get {
                return ResourceManager.GetString("EditorPleaseEnterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter {0} name ähnelt.
        /// </summary>
        internal static string EditorPleaseEnterName {
            get {
                return ResourceManager.GetString("EditorPleaseEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die an attribute ähnelt.
        /// </summary>
        internal static string EditorPleaseEnterNameAttribute {
            get {
                return ResourceManager.GetString("EditorPleaseEnterNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die a function ähnelt.
        /// </summary>
        internal static string EditorPleaseEnterNameFunction {
            get {
                return ResourceManager.GetString("EditorPleaseEnterNameFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die an object ähnelt.
        /// </summary>
        internal static string EditorPleaseEnterNameObject {
            get {
                return ResourceManager.GetString("EditorPleaseEnterNameObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die a variable ähnelt.
        /// </summary>
        internal static string EditorPleaseEnterNameVariable {
            get {
                return ResourceManager.GetString("EditorPleaseEnterNameVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a value ähnelt.
        /// </summary>
        internal static string EditorPleaseEnterValue {
            get {
                return ResourceManager.GetString("EditorPleaseEnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print a message ähnelt.
        /// </summary>
        internal static string EditorPrintMessage {
            get {
                return ResourceManager.GetString("EditorPrintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reload ähnelt.
        /// </summary>
        internal static string EditorReload {
            get {
                return ResourceManager.GetString("EditorReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove this item ähnelt.
        /// </summary>
        internal static string EditorRemoveThisItem {
            get {
                return ResourceManager.GetString("EditorRemoveThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replaced {0} occurrences. ähnelt.
        /// </summary>
        internal static string EditorReplacedOccurrences {
            get {
                return ResourceManager.GetString("EditorReplacedOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Require another object ähnelt.
        /// </summary>
        internal static string EditorRequireAnotherObject {
            get {
                return ResourceManager.GetString("EditorRequireAnotherObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run a script ähnelt.
        /// </summary>
        internal static string EditorRunScript {
            get {
                return ResourceManager.GetString("EditorRunScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you wish to save your changes before closing? ähnelt.
        /// </summary>
        internal static string EditorSaveBeforeClosing {
            get {
                return ResourceManager.GetString("EditorSaveBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you wish to save your changes before editing this game in the code view? ähnelt.
        /// </summary>
        internal static string EditorSaveBeforeEditingThisGame {
            get {
                return ResourceManager.GetString("EditorSaveBeforeEditingThisGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you wish to save your changes before leaving the code view? ähnelt.
        /// </summary>
        internal static string EditorSaveBeforeLeavingCodeView {
            get {
                return ResourceManager.GetString("EditorSaveBeforeLeavingCodeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you wish to save your changes before creating a new game? ähnelt.
        /// </summary>
        internal static string EditorSaveChangesBeforeCreating {
            get {
                return ResourceManager.GetString("EditorSaveChangesBeforeCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you wish to save your changes before opening a new game? ähnelt.
        /// </summary>
        internal static string EditorSaveChangesBeforeOpening {
            get {
                return ResourceManager.GetString("EditorSaveChangesBeforeOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save this game and then click Reload to apply changes from updating Included Libraries. ähnelt.
        /// </summary>
        internal static string EditorSaveGameAndClickReload {
            get {
                return ResourceManager.GetString("EditorSaveGameAndClickReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you are editing your game, you must save it from the Editor screen. The Save command in a game is for saving your play progress. ähnelt.
        /// </summary>
        internal static string EditorSaveItFromEditorScreen {
            get {
                return ResourceManager.GetString("EditorSaveItFromEditorScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        internal static string EditorScriptAdderAdd {
            get {
                return ResourceManager.GetString("EditorScriptAdderAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string EditorScriptAdderClose {
            get {
                return ResourceManager.GetString("EditorScriptAdderClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Script Command ähnelt.
        /// </summary>
        internal static string EditorScriptAdderWindowTitle {
            get {
                return ResourceManager.GetString("EditorScriptAdderWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, an error occurred. ähnelt.
        /// </summary>
        internal static string EditorSorryErrorOccurred {
            get {
                return ResourceManager.GetString("EditorSorryErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text not found: {0} ähnelt.
        /// </summary>
        internal static string EditorTextNotFound {
            get {
                return ResourceManager.GetString("EditorTextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text Processor help ähnelt.
        /// </summary>
        internal static string EditorTextProcessorHelp {
            get {
                return ResourceManager.GetString("EditorTextProcessorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Then ähnelt.
        /// </summary>
        internal static string EditorThen {
            get {
                return ResourceManager.GetString("EditorThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To: ähnelt.
        /// </summary>
        internal static string EditorToLabel {
            get {
                return ResourceManager.GetString("EditorToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Script ähnelt.
        /// </summary>
        internal static string EditorToolBarAddScript {
            get {
                return ResourceManager.GetString("EditorToolBarAddScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Code View ähnelt.
        /// </summary>
        internal static string EditorToolBarCodeView {
            get {
                return ResourceManager.GetString("EditorToolBarCodeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        internal static string EditorToolBarCopy {
            get {
                return ResourceManager.GetString("EditorToolBarCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cut ähnelt.
        /// </summary>
        internal static string EditorToolBarCut {
            get {
                return ResourceManager.GetString("EditorToolBarCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string EditorToolBarDelete {
            get {
                return ResourceManager.GetString("EditorToolBarDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Make editable copy ähnelt.
        /// </summary>
        internal static string EditorToolBarMakeEditable {
            get {
                return ResourceManager.GetString("EditorToolBarMakeEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move down ähnelt.
        /// </summary>
        internal static string EditorToolBarMoveDown {
            get {
                return ResourceManager.GetString("EditorToolBarMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move up ähnelt.
        /// </summary>
        internal static string EditorToolBarMoveUp {
            get {
                return ResourceManager.GetString("EditorToolBarMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste ähnelt.
        /// </summary>
        internal static string EditorToolBarPaste {
            get {
                return ResourceManager.GetString("EditorToolBarPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pop out ähnelt.
        /// </summary>
        internal static string EditorToolBarPopOut {
            get {
                return ResourceManager.GetString("EditorToolBarPopOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type &apos;{0}&apos; is already inherited ähnelt.
        /// </summary>
        internal static string EditorTypAlreadyInherited {
            get {
                return ResourceManager.GetString("EditorTypAlreadyInherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type &apos;{0}&apos; does not exist ähnelt.
        /// </summary>
        internal static string EditorTypNotExists {
            get {
                return ResourceManager.GetString("EditorTypNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to add attribute ähnelt.
        /// </summary>
        internal static string EditorUnableAddAttribute {
            get {
                return ResourceManager.GetString("EditorUnableAddAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to copy file. The following error occurred:{0} ähnelt.
        /// </summary>
        internal static string EditorUnableCopyFileErrorOccurred {
            get {
                return ResourceManager.GetString("EditorUnableCopyFileErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to create file. The following error occurred:{0} ähnelt.
        /// </summary>
        internal static string EditorUnableCreateFileErrorOccured {
            get {
                return ResourceManager.GetString("EditorUnableCreateFileErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to delete file:  ähnelt.
        /// </summary>
        internal static string EditorUnableDeleteFile {
            get {
                return ResourceManager.GetString("EditorUnableDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to publish game ähnelt.
        /// </summary>
        internal static string EditorUnablePublishGame {
            get {
                return ResourceManager.GetString("EditorUnablePublishGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to save the file due to the following error: ähnelt.
        /// </summary>
        internal static string EditorUnableSaveFileError {
            get {
                return ResourceManager.GetString("EditorUnableSaveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to set attribute value ähnelt.
        /// </summary>
        internal static string EditorUnableSetAttributeValue {
            get {
                return ResourceManager.GetString("EditorUnableSetAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to add data ähnelt.
        /// </summary>
        internal static string EditorUnableToAdddata {
            get {
                return ResourceManager.GetString("EditorUnableToAdddata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to add element ähnelt.
        /// </summary>
        internal static string EditorUnableToAddEmement {
            get {
                return ResourceManager.GetString("EditorUnableToAddEmement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to add item ähnelt.
        /// </summary>
        internal static string EditorUnableToAddItem {
            get {
                return ResourceManager.GetString("EditorUnableToAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to add page ähnelt.
        /// </summary>
        internal static string EditorUnableToAddPage {
            get {
                return ResourceManager.GetString("EditorUnableToAddPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to add type ähnelt.
        /// </summary>
        internal static string EditorUnableToAddType {
            get {
                return ResourceManager.GetString("EditorUnableToAddType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to add verb ähnelt.
        /// </summary>
        internal static string EditorUnableToAddVerb {
            get {
                return ResourceManager.GetString("EditorUnableToAddVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to save the file due to the following error: ähnelt.
        /// </summary>
        internal static string EditorUnableToSave {
            get {
                return ResourceManager.GetString("EditorUnableToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to set &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string EditorUnableToSet {
            get {
                return ResourceManager.GetString("EditorUnableToSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unhandled event ähnelt.
        /// </summary>
        internal static string EditorUnhandledEvent {
            get {
                return ResourceManager.GetString("EditorUnhandledEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown attribute type for DisplayString ähnelt.
        /// </summary>
        internal static string EditorUnknownAttributeTypeDisplayString {
            get {
                return ResourceManager.GetString("EditorUnknownAttributeTypeDisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown control type ähnelt.
        /// </summary>
        internal static string EditorUnknownControlType {
            get {
                return ResourceManager.GetString("EditorUnknownControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown dictionary type ähnelt.
        /// </summary>
        internal static string EditorUnknownDictionaryType {
            get {
                return ResourceManager.GetString("EditorUnknownDictionaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown direction {0} ähnelt.
        /// </summary>
        internal static string EditorUnknownDirection {
            get {
                return ResourceManager.GetString("EditorUnknownDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown list type ähnelt.
        /// </summary>
        internal static string EditorUnknownListType {
            get {
                return ResourceManager.GetString("EditorUnknownListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown source list for dropdown ähnelt.
        /// </summary>
        internal static string EditorUnknownSourceListForDropdown {
            get {
                return ResourceManager.GetString("EditorUnknownSourceListForDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unrecognised &apos;else if&apos; attribute ähnelt.
        /// </summary>
        internal static string EditorUnrecognisedElseIfAttribute {
            get {
                return ResourceManager.GetString("EditorUnrecognisedElseIfAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unrecognised file type. This game cannot be loaded in Quest. ähnelt.
        /// </summary>
        internal static string EditorUnrecognisedFileType {
            get {
                return ResourceManager.GetString("EditorUnrecognisedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unrecognised &apos;if&apos; attribute ähnelt.
        /// </summary>
        internal static string EditorUnrecogniseIfAttribute {
            get {
                return ResourceManager.GetString("EditorUnrecogniseIfAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have unsaved changes. ähnelt.
        /// </summary>
        internal static string EditorUnsavedChanges {
            get {
                return ResourceManager.GetString("EditorUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The player object cannot be renamed ähnelt.
        /// </summary>
        internal static string EditorValMsgCannotRenamePlayerElement {
            get {
                return ResourceManager.GetString("EditorValMsgCannotRenamePlayerElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Circular type reference ähnelt.
        /// </summary>
        internal static string EditorValMsgCircularTypeReference {
            get {
                return ResourceManager.GetString("EditorValMsgCircularTypeReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An element called &apos;{0}&apos; already exists in this game ähnelt.
        /// </summary>
        internal static string EditorValMsgElementAlreadyExists {
            get {
                return ResourceManager.GetString("EditorValMsgElementAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid attribute name ähnelt.
        /// </summary>
        internal static string EditorValMsgInvalidAttributeName1 {
            get {
                return ResourceManager.GetString("EditorValMsgInvalidAttributeName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred: {1} ähnelt.
        /// </summary>
        internal static string EditorValMsgInvalidAttributeName2 {
            get {
                return ResourceManager.GetString("EditorValMsgInvalidAttributeName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid element name ähnelt.
        /// </summary>
        internal static string EditorValMsgInvalidElementName {
            get {
                return ResourceManager.GetString("EditorValMsgInvalidElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid element name. Elements cannot contain these words:  ähnelt.
        /// </summary>
        internal static string EditorValMsgInvalidElementNameInvalidWord {
            get {
                return ResourceManager.GetString("EditorValMsgInvalidElementNameInvalidWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid element name. An element name cannot start or end with a space, and cannot contain multiple consecutive spaces. ähnelt.
        /// </summary>
        internal static string EditorValMsgInvalidElementNameMultipleSpaces {
            get {
                return ResourceManager.GetString("EditorValMsgInvalidElementNameMultipleSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid element name. An element name cannot start with a number. ähnelt.
        /// </summary>
        internal static string EditorValMsgInvalidElementNameStartsWithNumber {
            get {
                return ResourceManager.GetString("EditorValMsgInvalidElementNameStartsWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Item &apos;{0}&apos; already exists in the list ähnelt.
        /// </summary>
        internal static string EditorValMsgItemAlreadyExists {
            get {
                return ResourceManager.GetString("EditorValMsgItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The number of opening brackets \&quot;(\&quot; does not match the number of closing brackets \&quot;)\&quot;. ähnelt.
        /// </summary>
        internal static string EditorValMsgMismatchingBrackets {
            get {
                return ResourceManager.GetString("EditorValMsgMismatchingBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing quote character (\&quot;) ähnelt.
        /// </summary>
        internal static string EditorValMsgMismatchingQuotes {
            get {
                return ResourceManager.GetString("EditorValMsgMismatchingQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No error ähnelt.
        /// </summary>
        internal static string EditorValMsgOK {
            get {
                return ResourceManager.GetString("EditorValMsgOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verb would clash with command:  ähnelt.
        /// </summary>
        internal static string EditorVerbWithCommand {
            get {
                return ResourceManager.GetString("EditorVerbWithCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Regex search ähnelt.
        /// </summary>
        internal static string FindControlchkBoxRegex {
            get {
                return ResourceManager.GetString("FindControlchkBoxRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string FindControlcmdClose {
            get {
                return ResourceManager.GetString("FindControlcmdClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find next ähnelt.
        /// </summary>
        internal static string FindControlcmdFind {
            get {
                return ResourceManager.GetString("FindControlcmdFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace ähnelt.
        /// </summary>
        internal static string FindControlcmdReplace {
            get {
                return ResourceManager.GetString("FindControlcmdReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace All ähnelt.
        /// </summary>
        internal static string FindControlcmdReplaceAll {
            get {
                return ResourceManager.GetString("FindControlcmdReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find: ähnelt.
        /// </summary>
        internal static string FindControllblFind {
            get {
                return ResourceManager.GetString("FindControllblFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace with: ähnelt.
        /// </summary>
        internal static string FindControllblReplace {
            get {
                return ResourceManager.GetString("FindControllblReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string LauncherCancel {
            get {
                return ResourceManager.GetString("LauncherCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click here to update ähnelt.
        /// </summary>
        internal static string LauncherClickHereToUpdate {
            get {
                return ResourceManager.GetString("LauncherClickHereToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create ähnelt.
        /// </summary>
        internal static string LauncherCreate {
            get {
                return ResourceManager.GetString("LauncherCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a new game ähnelt.
        /// </summary>
        internal static string LauncherCreateNewGame {
            get {
                return ResourceManager.GetString("LauncherCreateNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download ähnelt.
        /// </summary>
        internal static string LauncherDownload {
            get {
                return ResourceManager.GetString("LauncherDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download complete ähnelt.
        /// </summary>
        internal static string LauncherDownloadComplete {
            get {
                return ResourceManager.GetString("LauncherDownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading... ähnelt.
        /// </summary>
        internal static string LauncherDownloading {
            get {
                return ResourceManager.GetString("LauncherDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string LauncherEdit {
            get {
                return ResourceManager.GetString("LauncherEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Games ähnelt.
        /// </summary>
        internal static string LauncherGetGames {
            get {
                return ResourceManager.GetString("LauncherGetGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get help in the forums ähnelt.
        /// </summary>
        internal static string LauncherGetHelpInForums {
            get {
                return ResourceManager.GetString("LauncherGetHelpInForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New version available ähnelt.
        /// </summary>
        internal static string LauncherNewVersion {
            get {
                return ResourceManager.GetString("LauncherNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No reviews or comments ähnelt.
        /// </summary>
        internal static string LauncherNoReviewsOrComments {
            get {
                return ResourceManager.GetString("LauncherNoReviewsOrComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not downloaded ähnelt.
        /// </summary>
        internal static string LauncherNotDownloaded {
            get {
                return ResourceManager.GetString("LauncherNotDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open an existing game ähnelt.
        /// </summary>
        internal static string LauncherOpenExistingGame {
            get {
                return ResourceManager.GetString("LauncherOpenExistingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play ähnelt.
        /// </summary>
        internal static string LauncherPlay {
            get {
                return ResourceManager.GetString("LauncherPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read the Tutorial ähnelt.
        /// </summary>
        internal static string LauncherReadTutorial {
            get {
                return ResourceManager.GetString("LauncherReadTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent ähnelt.
        /// </summary>
        internal static string LauncherRecent {
            get {
                return ResourceManager.GetString("LauncherRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reviews and comments ähnelt.
        /// </summary>
        internal static string LauncherReviewsAndComments {
            get {
                return ResourceManager.GetString("LauncherReviewsAndComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print a message ähnelt.
        /// </summary>
        internal static string TypePrintMessage {
            get {
                return ResourceManager.GetString("TypePrintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Require another object ähnelt.
        /// </summary>
        internal static string TypeRequireAnotherObject {
            get {
                return ResourceManager.GetString("TypeRequireAnotherObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run script ähnelt.
        /// </summary>
        internal static string TypeRunScript {
            get {
                return ResourceManager.GetString("TypeRunScript", resourceCulture);
            }
        }
    }
}
