title: Quest 5 Docs
description: Documentation for the Quest 5 text adventure game engine
remote_theme: just-the-docs/just-the-docs
baseurl: /quest

search_enabled: true
search:
  heading_level: 2
  previews: 3

aux_links:
  "GitHub": "https://github.com/textadventures/quest"
  "Discord": "https://textadventures.co.uk/community/discord"

aux_links_new_tab: true

markdown: kramdown

callouts:
  warning:
    title: Warning
    color: red