name: Enforce Version Change

on:
  pull_request:
    branches:
      - release

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}

      - name: Check if VERSION has changed
        run: |
          if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q "^VERSION$"; then
            echo "✅ VERSION file has been updated"
          else
            echo "❌ VERSION file must be updated in this PR"
            exit 1
          fi
